name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
    - run: |
        cd client && docker build . --file Dockerfile --tag aca-client:$(date +%s)
        cd ..
        cd server && docker build . --file Dockerfile --tag aca-server:$(date +%s)
